cc_binary(
    name = "test_point",
    srcs = ["test_Point2D.cc"],
    visibility = ["//visibility:public"],
    copts = ["-Isrc/include"],
    deps = [
        "//src:point",
        "//src:computational_geometry_headers",
    ],
)